"""esquema inicial er v1.3

Revision ID: 0001
Revises:
Create Date: 2026-09-23 10:53:05.470246

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ataque_predefinido",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("tipo", sa.String(length=100), nullable=True),
        sa.Column("descripcion", sa.String(length=300), nullable=True),
        sa.Column(
            "nivel_dificultad",
            sa.Enum("BAJO", "MEDIO", "ALTO", name="niveldificultad"),
            server_default="MEDIO",
            nullable=False,
        ),
        sa.Column("tecnica_mitre_principal", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "empresa_cliente",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("razon_social", sa.String(length=200), nullable=False),
        sa.Column("nit", sa.String(length=30), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("cantidad_empleados", sa.Integer(), nullable=True),
        sa.Column("dominio_principal", sa.String(length=150), nullable=True),
        sa.Column("correo_contacto", sa.String(length=150), nullable=True),
        sa.Column("pais", sa.String(length=80), nullable=True),
        sa.Column("ciudad", sa.String(length=80), nullable=True),
        sa.Column(
            "fecha_registro",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nit"),
    )
    op.create_table(
        "plan_comercial",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("tipo", sa.Enum("INDIVIDUAL", "COMPLETO", name="tipoplan"), nullable=False),
        sa.Column("precio", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("duracion_dias", sa.Integer(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("descripcion", sa.String(length=300), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "empresa_simulada",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("empresa_cliente_id", sa.Integer(), nullable=False),
        sa.Column("nombre_generado", sa.String(length=200), nullable=False),
        sa.Column("sector_simulado", sa.String(length=100), nullable=True),
        sa.Column("plantilla_referencia", sa.String(length=100), nullable=True),
        sa.Column(
            "fecha_generacion",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_cliente_id"],
            ["empresa_cliente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plan_ataque",
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("ataque_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ataque_id"],
            ["ataque_predefinido.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan_comercial.id"],
        ),
        sa.PrimaryKeyConstraint("plan_id", "ataque_id"),
    )
    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("correo", sa.String(length=150), nullable=False),
        sa.Column("contrasena_hash", sa.String(length=255), nullable=False),
        sa.Column("rol", sa.Enum("ADMIN", "ANALISTA", "CLIENTE", name="rol"), nullable=False),
        sa.Column("empresa_cliente_id", sa.Integer(), nullable=True),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("ultimo_acceso", sa.DateTime(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "fecha_registro",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_cliente_id"],
            ["empresa_cliente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("correo"),
    )
    op.create_table(
        "activo_simulado",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("empresa_simulada_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=100), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("ip_simulada", sa.String(length=45), nullable=True),
        sa.Column("sistema_operativo", sa.String(length=100), nullable=True),
        sa.Column(
            "criticidad",
            sa.Enum("BAJA", "MEDIA", "ALTA", "CRITICA", name="criticidad"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_simulada_id"],
            ["empresa_simulada.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contratacion",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("empresa_cliente_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("codigo_cupon", sa.String(length=30), nullable=True),
        sa.Column(
            "estado_pago",
            sa.Enum("PENDIENTE", "FORMALIZADO", "CANCELADO", name="estadopago"),
            server_default="PENDIENTE",
            nullable=False,
        ),
        sa.Column(
            "fecha", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("fecha_vencimiento", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["empresa_cliente_id"],
            ["empresa_cliente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan_comercial.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auditoria",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contratacion_id", sa.Integer(), nullable=False),
        sa.Column("empresa_simulada_id", sa.Integer(), nullable=False),
        sa.Column("analista_usuario_id", sa.Integer(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum("PENDIENTE", "EN_PROCESO", "COMPLETADA", name="estadoauditoria"),
            server_default="PENDIENTE",
            nullable=False,
        ),
        sa.Column("observaciones", sa.String(length=500), nullable=True),
        sa.Column("fecha_inicio", sa.DateTime(), nullable=True),
        sa.Column("fecha_fin", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analista_usuario_id"],
            ["usuario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contratacion_id"],
            ["contratacion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["empresa_simulada_id"],
            ["empresa_simulada.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contratacion_id"),
    )
    op.create_table(
        "solicitud_contacto_whatsapp",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contratacion_id", sa.Integer(), nullable=False),
        sa.Column("numero_whatsapp", sa.String(length=20), nullable=True),
        sa.Column(
            "fecha", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "estado",
            sa.Enum("ENVIADA", "RESPONDIDA", "CERRADA", name="estadosolicitud"),
            server_default="ENVIADA",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contratacion_id"],
            ["contratacion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auditoria_ataque",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("auditoria_id", sa.Integer(), nullable=False),
        sa.Column("ataque_id", sa.Integer(), nullable=False),
        sa.Column("fecha_ejecucion", sa.DateTime(), nullable=True),
        sa.Column(
            "estado_ejecucion",
            sa.Enum("PENDIENTE", "EJECUTADO", "FALLIDO", name="estadoejecucion"),
            server_default="PENDIENTE",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ataque_id"],
            ["ataque_predefinido.id"],
        ),
        sa.ForeignKeyConstraint(
            ["auditoria_id"],
            ["auditoria.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auditoria_id", "ataque_id"),
    )
    op.create_table(
        "informe",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("auditoria_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("BORRADOR", "VALIDADO", name="estadoinforme"),
            server_default="BORRADOR",
            nullable=False,
        ),
        sa.Column(
            "formato",
            sa.Enum("PDF", "HTML", name="formatoinforme"),
            server_default="PDF",
            nullable=False,
        ),
        sa.Column("idioma", sa.String(length=10), server_default="es", nullable=False),
        sa.Column("url_descarga", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_generacion",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("validado_por_usuario_id", sa.Integer(), nullable=True),
        sa.Column("fecha_validacion", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["auditoria_id"],
            ["auditoria.id"],
        ),
        sa.ForeignKeyConstraint(
            ["validado_por_usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auditoria_id"),
    )
    op.create_table(
        "resultado_impacto",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("auditoria_ataque_id", sa.Integer(), nullable=False),
        sa.Column("impacto_tecnico", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("impacto_operacional", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("impacto_financiero", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("moneda", sa.String(length=3), server_default="COP", nullable=False),
        sa.Column(
            "nivel_riesgo",
            sa.Enum("BAJO", "MEDIO", "ALTO", "URGENTE", name="nivelriesgo"),
            nullable=False,
        ),
        sa.Column("probabilidad_ocurrencia", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("tiempo_recuperacion_horas", sa.Integer(), nullable=True),
        sa.Column(
            "fecha_calculo",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["auditoria_ataque_id"],
            ["auditoria_ataque.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auditoria_ataque_id"),
    )
    op.create_table(
        "vulnerabilidad",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("auditoria_ataque_id", sa.Integer(), nullable=False),
        sa.Column("activo_simulado_id", sa.Integer(), nullable=True),
        sa.Column(
            "objetivo_tipo",
            sa.Enum("ACTIVO", "PERSONA", name="objetivotipo"),
            server_default="ACTIVO",
            nullable=False,
        ),
        sa.Column("objetivo_descripcion", sa.String(length=200), nullable=True),
        sa.Column("descripcion", sa.String(length=500), nullable=False),
        sa.Column(
            "criticidad",
            sa.Enum("BAJA", "MEDIA", "ALTA", "CRITICA", name="criticidad"),
            nullable=False,
        ),
        sa.Column("cve_referencia", sa.String(length=20), nullable=True),
        sa.Column(
            "estado",
            sa.Enum("ABIERTA", "EN_REMEDIACION", "CERRADA", name="estadovulnerabilidad"),
            server_default="ABIERTA",
            nullable=False,
        ),
        sa.Column(
            "fecha_deteccion",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activo_simulado_id"],
            ["activo_simulado.id"],
        ),
        sa.ForeignKeyConstraint(
            ["auditoria_ataque_id"],
            ["auditoria_ataque.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recomendacion_mitigacion",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vulnerabilidad_id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=500), nullable=False),
        sa.Column(
            "prioridad",
            sa.Enum("BAJA", "MEDIA", "ALTA", name="prioridadrecomendacion"),
            server_default="MEDIA",
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum("PENDIENTE", "IMPLEMENTADA", name="estadorecomendacion"),
            server_default="PENDIENTE",
            nullable=False,
        ),
        sa.Column("costo_estimado", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["vulnerabilidad_id"],
            ["vulnerabilidad.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "mysql":
        for evento in ("INSERT", "UPDATE"):
            op.execute(
                f"CREATE TRIGGER trg_vulnerabilidad_objetivo_{evento.lower()} "
                f"BEFORE {evento} ON vulnerabilidad FOR EACH ROW {_TRIGGER_BODY}"
            )


# ER v1.3, sección 3: TRIGGERS en vez de CHECK porque MariaDB falla (Error 1901)
# al combinar CHECK con varias FOREIGN KEY en la misma tabla.
_TRIGGER_BODY = """
BEGIN
    IF NEW.objetivo_tipo = 'ACTIVO' AND NEW.activo_simulado_id IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'objetivo_tipo ACTIVO requiere activo_simulado_id';
    END IF;
    IF NEW.objetivo_tipo = 'PERSONA'
       AND (NEW.objetivo_descripcion IS NULL OR NEW.objetivo_descripcion = '') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'objetivo_tipo PERSONA requiere objetivo_descripcion';
    END IF;
END
"""


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "mysql":
        op.execute("DROP TRIGGER IF EXISTS trg_vulnerabilidad_objetivo_insert")
        op.execute("DROP TRIGGER IF EXISTS trg_vulnerabilidad_objetivo_update")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recomendacion_mitigacion")
    op.drop_table("vulnerabilidad")
    op.drop_table("resultado_impacto")
    op.drop_table("informe")
    op.drop_table("auditoria_ataque")
    op.drop_table("solicitud_contacto_whatsapp")
    op.drop_table("auditoria")
    op.drop_table("contratacion")
    op.drop_table("activo_simulado")
    op.drop_table("usuario")
    op.drop_table("plan_ataque")
    op.drop_table("empresa_simulada")
    op.drop_table("plan_comercial")
    op.drop_table("empresa_cliente")
    op.drop_table("ataque_predefinido")
    # ### end Alembic commands ###
